/**
 ******************************************************************************
 * @file    generate_itf.cpp
 * @brief   Regenerate zint_itf_vectors.hpp: ITF element widths from zint.
 ******************************************************************************
 *
 * The same argument as generate.cpp makes for Code 128. Itf.hpp's ten-row
 * table is held to the symbology's structure by the tests -- five elements a
 * digit, exactly two of them wide -- and a table that is self-consistently
 * wrong survives all of it. zint has its own table and its own interleaving,
 * so a width run it agrees with is one two implementations reached separately.
 *
 * Not part of the test build: it needs libzint, the tests must build without
 * it, and the vectors are data rather than something to recompute every run.
 *
 *   apt-get install -y libzint-dev
 *   g++ -std=c++17 -o generate_itf generate_itf.cpp -lzint \
 *       && ./generate_itf > zint_itf_vectors.hpp
 *
 * ## Two stated rules about the corpus
 *
 * **Even lengths only.** zint pads an odd-length id with a leading zero and
 * encodes the result; Itf.hpp refuses it, because a scanner would read the
 * padded number back and that is a number the wearer did not enter. Both
 * behaviours are defensible and they are not the same behaviour, so the
 * corpus stays where they agree and Itf_test.cpp covers the refusal directly.
 *
 * **zint's ratio is this encoder's ratio.** zint emits ITF at 3:1 -- its runs
 * are only ever 1 or 3 -- which is what makes a width-for-width diff possible
 * rather than a comparison of narrow/wide patterns. If a future zint changed
 * that, these vectors would stop matching for a reason that is not a bug here,
 * which is why the version is recorded below.
 *
 ******************************************************************************
 */

#include <zint.h>

#include <cstdio>
#include <cstring>
#include <string>

namespace
{

/// Even-length digit strings, spread over what decides an ITF encoding: every
/// digit in a bar position and every digit in a space position, every length
/// the app accepts, and runs of a single repeated digit.
const char *kCorpus[] = {
    // the shortest symbol, and both single-pair extremes
    "00", "99", "10", "01", "12",
    // every digit as a bar (0,2,4,6,8) and as a space (1,3,5,7,9)
    "0123456789",
    // and the other way round: bars 1,3,5,7,9, spaces 0,2,4,6,8
    "1032547698",
    // lengths, stepping by a pair
    "1234", "123456", "12345678", "1234567890", "123456789012",
    "12345678901234", "1234567890123456",
    // a repeated digit at several lengths -- adjacent identical elements are
    // where a run-length reading of the symbol could go wrong
    "0000", "9999", "00000000", "99999999", "9999999999999999",
    // ITF-14 shaped, the common real-world case
    "00012345678905", "12345678901231",
    // alternating and patterned
    "1010101010", "5555555555", "9876543210",
};

std::string escape(const char *s)
{
    std::string out;
    for (const char *p = s; *p; p++) {
        if (*p == '"' || *p == '\\') { out += '\\'; out += *p; }
        else out += *p;
    }
    return out;
}

} // namespace

int main()
{
    printf("/* GENERATED by oracle/generate_itf.cpp -- do not edit.\n");
    printf(" *\n");
    const int v = ZBarcode_Version();
    char version[32];
    snprintf(version, sizeof(version), "zint %d.%d.%d", v / 10000, (v / 100) % 100, v % 100);
    printf(" * Interleaved 2 of 5 element widths from %s, an independent\n", version);
    printf(" * implementation. Each entry is one id, the total in narrow elements, and\n");
    printf(" * the bar/space widths starting with a bar -- the form Barcode::Encoded uses.\n");
    printf(" *\n");
    printf(" * Even lengths only: zint pads an odd id with a leading zero and Itf.hpp\n");
    printf(" * refuses it. See the header of generate_itf.cpp.\n");
    printf(" */\n\n");
    printf("#ifndef ZINT_ITF_VECTORS_HPP\n#define ZINT_ITF_VECTORS_HPP\n\n");
    printf("namespace ZintItfVectors\n{\n\n");
    printf("constexpr char kZintVersion[] = \"%s\";\n\n", version);
    printf("struct Vector\n{\n    const char *id;\n    int         totalUnits;\n"
           "    const char *widths;\n};\n\n");
    printf("constexpr Vector kVectors[] = {\n");

    for (const char *d : kCorpus) {
        const size_t len = strlen(d);
        if (len % 2 != 0) {
            fprintf(stderr, "corpus entry %s is odd-length; see the header\n", d);
            return 1;
        }

        zint_symbol *s = ZBarcode_Create();
        s->symbology = BARCODE_C25INTER;
        s->show_hrt  = 0;
        if (ZBarcode_Encode(s, (const unsigned char *)d, (int)len) >= ZINT_ERROR) {
            fprintf(stderr, "zint refused %s: %s\n", d, s->errtxt);
            ZBarcode_Delete(s);
            return 1;
        }

        // zint must not have padded: if its human-readable text is not the id
        // we handed it, the two encoders are not describing the same number.
        if (strcmp((const char *)s->text, d) != 0) {
            fprintf(stderr, "zint rewrote %s as %s\n", d, s->text);
            ZBarcode_Delete(s);
            return 1;
        }

        std::string widths;
        int run = 0, prev = -1;
        for (int c = 0; c < s->width; c++) {
            const int bit = (s->encoded_data[0][c >> 3] >> (c & 7)) & 1;
            if (bit != prev && prev != -1) { widths += std::to_string(run); run = 0; }
            prev = bit; run++;
        }
        if (run) widths += std::to_string(run);

        printf("    { \"%s\", %d, \"%s\" },\n", escape(d).c_str(), s->width, widths.c_str());
        ZBarcode_Delete(s);
    }

    printf("};\n\nconstexpr int kVectorCount = sizeof(kVectors) / sizeof(kVectors[0]);\n\n");
    printf("} // namespace ZintItfVectors\n\n#endif // ZINT_ITF_VECTORS_HPP\n");
    return 0;
}
