/**
 ******************************************************************************
 * @file    generate.cpp
 * @brief   Regenerate zint_vectors.hpp: Code 128 module patterns from zint.
 ******************************************************************************
 *
 * The tests in this directory hold Code128.hpp's 107-row table to the
 * symbology's own structure, which catches a great deal but is not an oracle --
 * there is no second Code 128 implementation in the tree to diff against, and
 * a table that is self-consistently wrong would pass every structural test.
 *
 * This produces one. zint is an independent, widely used C implementation with
 * its own table and its own subset selection, so a module pattern it agrees
 * with is a pattern two implementations arrived at separately.
 *
 * Not part of the test build: it needs libzint, the tests must build without
 * it, and the vectors are data rather than something to recompute on every run.
 * Regenerate when the corpus changes:
 *
 *   apt-get install -y libzint-dev
 *   g++ -std=c++17 -o generate generate.cpp -lzint && ./generate > zint_vectors.hpp
 *
 * Recorded with the zint version, because a change in its subset policy would
 * otherwise look like a change in ours.
 *
 ******************************************************************************
 */

#include <zint.h>

#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

namespace
{

/// The corpus. Spread over the things that decide a Code 128 encoding: subset
/// boundaries, the ends of the printable range, digit runs of every parity and
/// position, and the ids this app actually exists for.
const char *kCorpus[] = {
    // single characters, and the ends of the printable range
    "A", "1", " ", "~", "!\"#$%&'()*+,-./",
    // no digit run long enough for either implementation to switch
    "A1", "AIM", "Z99", "Test-123", "hello world", "A1B2C3D4E5F6",
    "WWWWWWWWWWWW", "0123456789ABCDEF",
    // digit runs: every parity, and at the start, middle and end
    "12", "1234", "123456", "1234567", "12345678", "1234567890",
    "12345678901234", "123456789012345", "1234567890123456",
    "A1234567", "GYMWORLD12345678", "2005812", "AB123456CD", "1234AB5678",
    // the longest this app accepts, in both flavours
    "ABCDEFGHIJKLMNOP", "9999999999999999",
};

std::string escape(const char *s)
{
    std::string out;
    for (const char *p = s; *p; p++) {
        if (*p == '"' || *p == '\\') { out += '\\'; out += *p; }
        else out += *p;
    }
    return out;
}

} // namespace

int main()
{
    printf("/* GENERATED by oracle/generate.cpp -- do not edit.\n");
    printf(" *\n");
    const int v = ZBarcode_Version();
    char version[32];
    snprintf(version, sizeof(version), "zint %d.%d.%d", v / 10000, (v / 100) % 100, v % 100);
    printf(" * Code 128 module patterns from %s, an independent implementation.\n", version);
    printf(" * Each entry is one id, the module count, and the bar/space widths in\n");
    printf(" * modules starting with a bar -- the same form as Code128::Encoded.\n");
    printf(" */\n\n");
    printf("#ifndef ZINT_VECTORS_HPP\n#define ZINT_VECTORS_HPP\n\n");
    printf("namespace ZintVectors\n{\n\n");
    printf("constexpr char kZintVersion[] = \"%s\";\n\n", version);
    printf("struct Vector\n{\n    const char *id;\n    int         totalModules;\n"
           "    const char *widths;\n};\n\n");
    printf("constexpr Vector kVectors[] = {\n");

    for (const char *d : kCorpus) {
        zint_symbol *s = ZBarcode_Create();
        s->symbology = BARCODE_CODE128;
        s->show_hrt  = 0;
        if (ZBarcode_Encode(s, (const unsigned char *)d, (int)strlen(d)) >= ZINT_ERROR) {
            fprintf(stderr, "zint refused %s: %s\n", d, s->errtxt);
            ZBarcode_Delete(s);
            return 1;
        }
        std::string widths;
        int run = 0, prev = -1;
        for (int c = 0; c < s->width; c++) {
            const int bit = (s->encoded_data[0][c >> 3] >> (c & 7)) & 1;
            if (bit != prev && prev != -1) { widths += std::to_string(run); run = 0; }
            prev = bit; run++;
        }
        if (run) widths += std::to_string(run);
        printf("    { \"%s\", %d, \"%s\" },\n", escape(d).c_str(), s->width, widths.c_str());
        ZBarcode_Delete(s);
    }

    printf("};\n\nconstexpr int kVectorCount = sizeof(kVectors) / sizeof(kVectors[0]);\n\n");
    printf("} // namespace ZintVectors\n\n#endif // ZINT_VECTORS_HPP\n");
    return 0;
}
