[package]
name = "genericity"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "lib"]

[features]
default = []
concrete = []
generic = []
generic_two = []
generic_fast = []

[dependencies]
embedded-graphics = "0.8"

[profile.release]
panic = "abort"
opt-level = "z"
lto = true
codegen-units = 1
overflow-checks = false
