//! Text for `embedded-graphics` draw targets: Poppins pre-rendered at build time into 2bpp glyph
//! atlases, measured, aligned, wrapped and blitted. Design record: `README.md`, and `Docs/TEXT.md`
//! at the repo root for the measurements that chose this over the alternatives.
//!
//! A glyph's coverage is one of four levels, so the ink is blended toward the ground through
//! [`Ink`]; clipping belongs to the target, not to this crate.

#![cfg_attr(not(feature = "std"), no_std)]

use embedded_graphics::{
    prelude::{DrawTarget, Point},
    Pixel,
};

mod compose;
pub mod faces;

/// One glyph of a [`Face`]: where its pixels start in the face's bitstream and how to place it.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct Node {
    pub off: u32,
    pub cp: u16,
    pub w: u8,
    pub h: u8,
    /// Rows from the baseline up to the top of the ink.
    pub top: i8,
    /// Columns from the pen to the left edge of the ink.
    pub left: i8,
    pub adv: u8,
    pub flags: u8,
}

const _: () = assert!(core::mem::size_of::<Node>() == 12);

/// One weight at one pixel size over one character set, generated by `Tools/atlas.py`.
pub struct Face {
    pub px: u8,
    pub ascent: u8,
    pub descent: u8,
    pub flags: u8,
    pub nodes: &'static [Node],
    pub data: &'static [u8],
}

/// What a string takes up, in pixels along the baseline from the pen's start.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Measure {
    /// Sum of advances: what alignment and wrapping use, as TouchGFX's `getStringWidth` did.
    pub advance: i32,
    /// Leftmost inked column relative to the pen's start; 0 for an empty string.
    pub ink_left: i32,
    /// One past the rightmost inked column; 0 for an empty string.
    pub ink_right: i32,
    /// Characters that had no glyph and were drawn as a box, saturating.
    pub missing: u8,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Align {
    Left,
    Center,
    Right,
}

/// A colour that a glyph's partial coverage can be blended in.
///
/// Atlas coverage is quantised to four levels, so `level` runs 0 to 3 and 3 is fully inked.
pub trait Ink: Copy {
    /// This ink at `level` of three over `ground`.
    fn shade(self, ground: Self, level: u8) -> Self;
}

#[cfg(feature = "abgr2222")]
impl Ink for inscribed_disc::Abgr2222 {
    fn shade(self, ground: Self, level: u8) -> Self {
        inscribed_disc::color::shade(self, ground, level)
    }
}

/// How a run of text is coloured and where its advance sits relative to the `x` it is drawn at.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Style<C> {
    pub ink: C,
    /// What a partially covered pixel is blended toward: whatever the screen already holds.
    pub ground: C,
    pub align: Align,
}

impl<C> Style<C> {
    pub fn new(ink: C, ground: C, align: Align) -> Self {
        Style { ink, ground, align }
    }

    /// The pen starts at `x`.
    pub fn left(ink: C, ground: C) -> Self {
        Style::new(ink, ground, Align::Left)
    }

    /// The advance is centred on `x`.
    pub fn centered(ink: C, ground: C) -> Self {
        Style::new(ink, ground, Align::Center)
    }

    /// The advance ends at `x`.
    pub fn right(ink: C, ground: C) -> Self {
        Style::new(ink, ground, Align::Right)
    }
}

fn is_combining(c: char) -> bool {
    ('\u{0300}'..='\u{036F}').contains(&c)
}

fn compose(base: char, mark: char) -> Option<char> {
    let (b, m) = (base as u32, mark as u32);
    if b > 0xFFFF || m > 0xFFFF {
        return None;
    }
    compose::COMPOSE
        .binary_search_by_key(&(b as u16, m as u16), |&(cb, cm, _)| (cb, cm))
        .ok()
        .and_then(|i| char::from_u32(compose::COMPOSE[i].2 as u32))
}

/// The characters of `text` as the face will look them up: a base letter followed by a combining
/// mark becomes its precomposed form when Latin has one; otherwise both pass through unchanged and
/// the mark draws as a missing glyph on its own.
pub fn chars(text: &str) -> impl Iterator<Item = char> + '_ {
    let mut it = text.chars().peekable();
    core::iter::from_fn(move || {
        let c = it.next()?;
        if let Some(&next) = it.peek() {
            if is_combining(next) {
                if let Some(composed) = compose(c, next) {
                    it.next();
                    return Some(composed);
                }
            }
        }
        Some(c)
    })
}

enum Glyph<'f> {
    Node(&'f Node),
    /// A one-pixel hollow box: visible, never a plausible wrong letter.
    Missing { w: i32, h: i32, adv: i32 },
}

impl Face {
    pub fn glyph(&self, c: char) -> Option<&Node> {
        let cp = c as u32;
        if cp > 0xFFFF {
            return None;
        }
        self.nodes
            .binary_search_by_key(&(cp as u16), |n| n.cp)
            .ok()
            .map(|i| &self.nodes[i])
    }

    /// Whether every character of `text` has a glyph, after composition.
    pub fn covers(&self, text: &str) -> bool {
        chars(text).all(|c| self.glyph(c).is_some())
    }

    /// Ascent plus descent: the rows one line of this face may touch.
    pub fn line_height(&self) -> i32 {
        self.ascent as i32 + self.descent as i32
    }

    fn lookup(&self, c: char) -> Glyph<'_> {
        match self.glyph(c) {
            Some(n) => Glyph::Node(n),
            None => {
                let px = self.px as i32;
                let w = (px * 3 / 5).max(3);
                Glyph::Missing { w, h: (px * 7 / 10).max(3), adv: w + (px / 10).max(1) }
            }
        }
    }

    pub fn measure(&self, text: &str) -> Measure {
        let mut m = Measure::default();
        let mut first = true;
        for c in chars(text) {
            let (left, right, adv) = match self.lookup(c) {
                Glyph::Node(n) => (n.left as i32, n.left as i32 + n.w as i32, n.adv as i32),
                Glyph::Missing { w, adv, .. } => {
                    m.missing = m.missing.saturating_add(1);
                    (0, w, adv)
                }
            };
            if right > left {
                let (l, r) = (m.advance + left, m.advance + right);
                if first {
                    m.ink_left = l;
                    m.ink_right = r;
                    first = false;
                } else {
                    m.ink_left = m.ink_left.min(l);
                    m.ink_right = m.ink_right.max(r);
                }
            }
            m.advance += adv;
        }
        m
    }

    fn level(&self, node: &Node, col: i32, row: i32) -> u8 {
        let i = node.off as usize * 4 + (row * node.w as i32 + col) as usize;
        (self.data[i / 4] >> (2 * (i % 4))) & 3
    }

    /// Draws `text` on `baseline`, placed at `x` as the style's alignment says, and returns what
    /// it measured.
    pub fn draw<D>(
        &self,
        target: &mut D,
        text: &str,
        x: i32,
        baseline: i32,
        style: Style<D::Color>,
    ) -> Result<Measure, D::Error>
    where
        D: DrawTarget,
        D::Color: Ink,
    {
        let m = self.measure(text);
        // Three shades exist, not one a pixel.
        let ramp = [
            style.ink.shade(style.ground, 1),
            style.ink.shade(style.ground, 2),
            style.ink.shade(style.ground, 3),
        ];
        let mut pen = match style.align {
            Align::Left => x,
            Align::Center => x - m.advance / 2,
            Align::Right => x - m.advance,
        };
        for c in chars(text) {
            match self.lookup(c) {
                Glyph::Node(n) => {
                    let x0 = pen + n.left as i32;
                    let y0 = baseline - n.top as i32;
                    let (w, h) = (n.w as i32, n.h as i32);
                    target.draw_iter((0..w * h).filter_map(|i| {
                        match self.level(n, i % w, i / w) {
                            0 => None,
                            level => Some(Pixel(
                                Point::new(x0 + i % w, y0 + i / w),
                                ramp[level as usize - 1],
                            )),
                        }
                    }))?;
                    pen += n.adv as i32;
                }
                Glyph::Missing { w, h, adv } => {
                    let y0 = baseline - h;
                    let top = (0..w).map(move |i| (pen + i, y0));
                    let bottom = (0..w).map(move |i| (pen + i, baseline - 1));
                    let left = (0..h).map(move |j| (pen, y0 + j));
                    let right = (0..h).map(move |j| (pen + w - 1, y0 + j));
                    target.draw_iter(
                        top.chain(bottom)
                            .chain(left)
                            .chain(right)
                            .map(|(x, y)| Pixel(Point::new(x, y), style.ink)),
                    )?;
                    pen += adv;
                }
            }
        }
        Ok(m)
    }

    /// [`Face::draw`] with the line's top at `top` instead of its baseline.
    pub fn draw_top<D>(
        &self,
        target: &mut D,
        text: &str,
        x: i32,
        top: i32,
        style: Style<D::Color>,
    ) -> Result<Measure, D::Error>
    where
        D: DrawTarget,
        D::Color: Ink,
    {
        self.draw(target, text, x, top + self.ascent as i32, style)
    }

    /// Greedy word wrap against `max_width`, filling `lines` in order. Returns how many lines the
    /// whole text needs, which exceeds `lines.len()` when it did not fit; a word wider than the
    /// width sits alone on its line rather than being split.
    pub fn wrap<'t>(&self, text: &'t str, max_width: i32, lines: &mut [&'t str]) -> usize {
        let mut count = 0;
        let mut line_start = 0usize;
        let mut line_end = 0usize;
        let emit = |lines: &mut [&'t str], s: &'t str, count: &mut usize| {
            if s.is_empty() {
                return;
            }
            if *count < lines.len() {
                lines[*count] = s;
            }
            *count += 1;
        };
        let word_ends = text
            .char_indices()
            .filter(|&(_, c)| c == ' ')
            .map(|(i, _)| i)
            .chain(core::iter::once(text.len()));
        for word_end in word_ends {
            if word_end <= line_end {
                continue;
            }
            let candidate = text[line_start..word_end].trim();
            if self.measure(candidate).advance <= max_width || line_end == line_start {
                line_end = word_end;
            } else {
                emit(lines, text[line_start..line_end].trim(), &mut count);
                line_start = line_end + 1;
                line_end = word_end.max(line_start);
            }
        }
        if line_start < text.len() {
            emit(lines, text[line_start..].trim(), &mut count);
        }
        count
    }
}

/// The first of `faces` whose advance for `text` fits `max_width`: the size ladder.
pub fn pick<'f>(faces: &[&'f Face], text: &str, max_width: i32) -> Option<&'f Face> {
    faces.iter().copied().find(|f| f.measure(text).advance <= max_width)
}

#[cfg(test)]
mod tests {
    use super::faces::*;
    use super::*;
    use inscribed_disc::{Abgr2222, Surface};

    const W: u32 = 240;
    const H: u32 = 240;

    const WHITE: Abgr2222 = Abgr2222::WHITE;
    const BLACK: Abgr2222 = Abgr2222::BLACK;

    fn on_white(f: impl FnOnce(&mut Surface<Abgr2222>)) -> Vec<u8> {
        let mut buf = vec![0u8; (W * H) as usize];
        let mut s = Surface::<Abgr2222>::rect(&mut buf, W, H).unwrap();
        f(&mut s);
        buf
    }

    fn all_faces() -> Vec<(&'static str, &'static Face)> {
        vec![
            ("SEMIBOLD_18_ASCII", &SEMIBOLD_18_ASCII),
            ("REGULAR_14_ASCII", &REGULAR_14_ASCII),
            ("REGULAR_12_ASCII", &REGULAR_12_ASCII),
            ("SEMIBOLD_20_ASCII", &SEMIBOLD_20_ASCII),
            ("REGULAR_18_LATIN", &REGULAR_18_LATIN),
            ("REGULAR_16_LATIN", &REGULAR_16_LATIN),
            ("SEMIBOLD_24_ANSWERS", &SEMIBOLD_24_ANSWERS),
            ("SEMIBOLD_32_TITLE", &SEMIBOLD_32_TITLE),
            ("SEMIBOLD_27_CLOCK", &SEMIBOLD_27_CLOCK),
            ("SEMIBOLD_36_CLOCK", &SEMIBOLD_36_CLOCK),
            ("SEMIBOLD_49_CLOCK", &SEMIBOLD_49_CLOCK),
            ("SEMIBOLD_60_CLOCK", &SEMIBOLD_60_CLOCK),
        ]
    }

    #[test]
    fn every_face_is_well_formed() {
        for (name, f) in all_faces() {
            assert!(f.nodes.windows(2).all(|p| p[0].cp < p[1].cp), "{name}: nodes not sorted by code point");
            for n in f.nodes {
                let bits = n.w as usize * n.h as usize * 2;
                assert!(n.off as usize + bits.div_ceil(8) <= f.data.len(), "{name}: U+{:04X} runs past the bitstream", n.cp);
                assert!(n.h as i32 <= f.line_height() + 2, "{name}: U+{:04X} taller than the line", n.cp);
            }
            assert!(f.glyph(' ').is_some(), "{name}: no space");
        }
    }

    /// Barcode's README measured these with TouchGFX's own `getStringWidth` on the faces it shipped.
    #[test]
    fn advances_match_the_touchgfx_build_barcode_measured() {
        assert_eq!(SEMIBOLD_20_ASCII.measure("0123456789ABC").advance, 172);
        assert_eq!(SEMIBOLD_20_ASCII.measure("0123456789ABCD").advance, 186);
        assert_eq!(SEMIBOLD_20_ASCII.measure("0123456789ABCDE").advance, 197);
        assert_eq!(SEMIBOLD_20_ASCII.measure("0123456789ABCDEF").advance, 208);
        assert_eq!(SEMIBOLD_20_ASCII.measure("GYMWORLD12345678").advance, 222);
        assert_eq!(SEMIBOLD_20_ASCII.measure("WWWWWWWWWWWW").advance, 240);
        assert_eq!(REGULAR_18_LATIN.measure("0123456789ABCD").advance, 160);
        assert_eq!(REGULAR_18_LATIN.measure("0123456789ABCDEF").advance, 178);
        assert_eq!(REGULAR_18_LATIN.measure("GYMWORLD12345678").advance, 193);
        assert_eq!(REGULAR_18_LATIN.measure("WWWWWWWWWWWW").advance, 216);
    }

    #[test]
    fn latin_faces_cover_tier_one_and_ascii_faces_do_not() {
        assert!(REGULAR_18_LATIN.covers("José Zoë Müller Søren Łukasz ° µ ± … – — “ ” €"));
        assert!(!SEMIBOLD_20_ASCII.covers("é"));
        assert!(!REGULAR_18_LATIN.covers("′"), "Poppins has no prime");
    }

    #[test]
    fn a_decomposed_accent_is_composed_before_lookup() {
        let composed: Vec<char> = chars("Jose\u{0301}").collect();
        assert_eq!(composed, vec!['J', 'o', 's', 'é']);
        assert!(REGULAR_18_LATIN.covers("Jose\u{0301}"));
        assert_eq!(REGULAR_18_LATIN.measure("Jose\u{0301}"), REGULAR_18_LATIN.measure("José"));
    }

    #[test]
    fn a_missing_glyph_is_counted_and_drawn_as_a_box() {
        let m = SEMIBOLD_20_ASCII.measure("aé");
        assert_eq!(m.missing, 1);
        let buf = on_white(|s| {
            SEMIBOLD_20_ASCII.draw(s, "é", 100, 100, Style::left(WHITE, BLACK)).unwrap();
        });
        let lit = buf.iter().filter(|&&b| b != 0).count();
        assert!(lit > 20 && lit < 80, "a hollow box, not a filled one or nothing: {lit} lit");
        assert_eq!(buf[(99 * 240 + 100) as usize], WHITE.0, "box corner at the pen, on the baseline's row above");
    }

    #[test]
    fn alignment_places_the_advance_where_it_says() {
        let text = "0123456789ABCD";
        let adv = SEMIBOLD_20_ASCII.measure(text).advance;
        for (align, x, expected_left_pen) in [(Align::Left, 30, 30), (Align::Center, 120, 120 - adv / 2), (Align::Right, 200, 200 - adv)] {
            let mut m = Measure::default();
            let buf = on_white(|s| {
                m = SEMIBOLD_20_ASCII.draw(s, text, x, 120, Style::new(WHITE, BLACK, align)).unwrap();
            });
            let first_lit_col = (0..240).find(|&x| (0..240).any(|y| buf[(y * 240 + x) as usize] != 0)).unwrap();
            assert_eq!(first_lit_col, expected_left_pen + m.ink_left, "{align:?}");
        }
    }

    /// Glyphs reach the buffer through `draw_iter`, so a target that clips gets to; writing bytes
    /// straight into the framebuffer would silently stop honouring it. The rule is inscribed-disc's.
    #[test]
    fn a_clipping_target_still_clips_what_this_crate_draws() {
        let mut buf = vec![0u8; (W * H) as usize];
        let mut c = Surface::<Abgr2222>::round(&mut buf, W, H).unwrap();
        for y in [10, 30, 120, 210, 230] {
            SEMIBOLD_20_ASCII
                .draw(&mut c, "WWWWWWWWWWWWWWWWWWWWWWWW", 120, y, Style::centered(WHITE, BLACK))
                .unwrap();
        }
        for y in 0..240i32 {
            for x in 0..240i32 {
                let lit = (2 * x - 239).pow(2) + (2 * y - 239).pow(2) <= 239 * 239;
                if !lit {
                    assert_eq!(buf[(y * 240 + x) as usize], 0, "({x},{y}) is behind the bezel");
                }
            }
        }
        assert!(buf.iter().any(|&b| b != 0));
    }

    /// The four atlas levels reach the four the panel has; the arithmetic is inscribed-disc's.
    #[test]
    fn ink_spans_the_grey_levels_it_is_given() {
        let levels: Vec<u8> = (0..=3).map(|l| WHITE.shade(BLACK, l).0 & 3).collect();
        assert_eq!(levels, vec![0, 1, 2, 3]);
        assert_eq!(WHITE.shade(BLACK, 3), WHITE);
        assert_eq!(WHITE.shade(BLACK, 0), BLACK);
    }

    #[test]
    fn drawn_text_uses_all_four_levels() {
        let buf = on_white(|s| {
            REGULAR_18_LATIN.draw(s, "Set it to Code128,", 120, 120, Style::centered(WHITE, BLACK)).unwrap();
        });
        for level in 1..=3u8 {
            assert!(buf.contains(&WHITE.shade(BLACK, level).0), "level {level} never drawn");
        }
    }

    #[test]
    fn wrap_never_exceeds_the_width_never_splits_a_word_and_loses_nothing() {
        let text = "No codes yet. Set one in the UNA app, or write input.json.";
        let mut lines = [""; 4];
        let n = REGULAR_18_LATIN.wrap(text, 200, &mut lines);
        assert!(n <= 4, "needs {n} lines");
        let mut words = Vec::new();
        for line in &lines[..n] {
            assert!(REGULAR_18_LATIN.measure(line).advance <= 200, "{line:?} too wide");
            words.extend(line.split(' '));
        }
        assert_eq!(words, text.split(' ').collect::<Vec<_>>());
    }

    #[test]
    fn wrap_reports_overflow_instead_of_dropping_lines() {
        let text = "one two three four five six seven eight nine ten eleven twelve";
        let mut lines = [""; 2];
        let n = REGULAR_18_LATIN.wrap(text, 60, &mut lines);
        assert!(n > 2);
        assert_eq!(lines[0], "one");
    }

    #[test]
    fn a_word_wider_than_the_box_sits_alone_rather_than_being_split() {
        let mut lines = [""; 3];
        let n = REGULAR_18_LATIN.wrap("a WWWWWWWWWWWWWWWWWWWW b", 60, &mut lines);
        assert_eq!(n, 3);
        assert_eq!(lines[1], "WWWWWWWWWWWWWWWWWWWW");
    }

    #[test]
    fn pick_walks_the_ladder() {
        let ladder = [&SEMIBOLD_20_ASCII, &REGULAR_18_LATIN];
        assert!(core::ptr::eq(pick(&ladder, "0123456789ABCD", 187).unwrap(), &SEMIBOLD_20_ASCII));
        assert!(core::ptr::eq(pick(&ladder, "0123456789ABCDE", 187).unwrap(), &REGULAR_18_LATIN));
        assert!(pick(&ladder, "GYMWORLD12345678", 187).is_none());
    }

    #[test]
    fn draw_top_puts_the_ascent_above_the_top() {
        let buf = on_white(|s| {
            SEMIBOLD_20_ASCII.draw_top(s, "H", 20, 50, Style::left(WHITE, BLACK)).unwrap();
        });
        let first_row = (0..240).find(|&y| (0..240).any(|x| buf[y * 240 + x] != 0)).unwrap();
        assert!(first_row >= 50 && first_row < 50 + SEMIBOLD_20_ASCII.ascent as usize);
    }
}
