//! Text for the Rust GUIs: Poppins pre-rendered at build time into 2bpp glyph atlases, blitted
//! onto an `ABGR2222` framebuffer through the lit disc. Design record: `README.md`, and
//! `Docs/TEXT.md` at the repo root for the measurements that chose this over the alternatives.
//!
//! PANEL. 240x240, round, four levels a channel, so a glyph's coverage is one of four shades and
//! nothing outside the inscribed disc is glass. Falsified by a different display; `Canvas::round`
//! is the rule, `nothing_is_lit_outside_the_disc` holds it.

#![cfg_attr(not(feature = "std"), no_std)]

mod compose;
pub mod faces;

/// One glyph of a [`Face`]: where its pixels start in the face's bitstream and how to place it.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct Node {
    pub off: u32,
    pub cp: u16,
    pub w: u8,
    pub h: u8,
    /// Rows from the baseline up to the top of the ink.
    pub top: i8,
    /// Columns from the pen to the left edge of the ink.
    pub left: i8,
    pub adv: u8,
    pub flags: u8,
}

const _: () = assert!(core::mem::size_of::<Node>() == 12);

/// One weight at one pixel size over one character set, generated by `Tools/atlas.py`.
pub struct Face {
    pub px: u8,
    pub ascent: u8,
    pub descent: u8,
    pub flags: u8,
    pub nodes: &'static [Node],
    pub data: &'static [u8],
}

/// What a string takes up, in pixels along the baseline from the pen's start.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Measure {
    /// Sum of advances: what alignment and wrapping use, as TouchGFX's `getStringWidth` did.
    pub advance: i32,
    /// Leftmost inked column relative to the pen's start; 0 for an empty string.
    pub ink_left: i32,
    /// One past the rightmost inked column; 0 for an empty string.
    pub ink_right: i32,
    /// Characters that had no glyph and were drawn as a box, saturating.
    pub missing: u8,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Align {
    Left,
    Center,
    Right,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Clip {
    /// The inscribed disc of the canvas, by `BarcodeLayout::pixelIsLit`'s rule.
    Disc,
    Rect,
}

/// An `ABGR2222` framebuffer to draw into, one byte a pixel, row-major.
pub struct Canvas<'a> {
    buf: &'a mut [u8],
    w: i32,
    h: i32,
    clip: Clip,
    /// What a partially covered pixel is blended toward.
    ground: u8,
}

pub const BLACK: u8 = 0xC0;
pub const WHITE: u8 = 0xFF;

impl<'a> Canvas<'a> {
    /// The watch: only the inscribed disc is glass.
    pub fn round(buf: &'a mut [u8], w: u32, h: u32) -> Self {
        Self::new(buf, w, h, Clip::Disc)
    }

    /// A square target with no bezel, for tests and host tools.
    pub fn rect(buf: &'a mut [u8], w: u32, h: u32) -> Self {
        Self::new(buf, w, h, Clip::Rect)
    }

    fn new(buf: &'a mut [u8], w: u32, h: u32, clip: Clip) -> Self {
        let needed = (w as usize).saturating_mul(h as usize);
        assert!(buf.len() >= needed, "canvas smaller than its stated geometry");
        Canvas { buf, w: w as i32, h: h as i32, clip, ground: BLACK }
    }

    /// Partial coverage blends toward this colour; black unless the screen is filled otherwise.
    pub fn with_ground(mut self, ground: u8) -> Self {
        self.ground = ground;
        self
    }

    pub fn width(&self) -> i32 {
        self.w
    }

    pub fn height(&self) -> i32 {
        self.h
    }

    /// Whether the panel would show this pixel at all.
    pub fn is_lit(&self, x: i32, y: i32) -> bool {
        if x < 0 || y < 0 || x >= self.w || y >= self.h {
            return false;
        }
        match self.clip {
            Clip::Rect => true,
            Clip::Disc => {
                let dx = 2 * x - (self.w - 1);
                let dy = 2 * y - (self.h - 1);
                let d = self.w.min(self.h) - 1;
                dx * dx + dy * dy <= d * d
            }
        }
    }

    fn put(&mut self, x: i32, y: i32, color: u8) {
        if self.is_lit(x, y) {
            self.buf[(y * self.w + x) as usize] = color;
        }
    }
}

/// `ink` at `level` of three over `ground`, channel by channel, rounded.
pub fn shade(ink: u8, ground: u8, level: u8) -> u8 {
    let ch = |shift: u8| {
        let i = ((ink >> shift) & 3) as u16;
        let g = ((ground >> shift) & 3) as u16;
        ((i * level as u16 + g * (3 - level as u16) + 1) / 3) as u8
    };
    0xC0 | ch(0) | (ch(2) << 2) | (ch(4) << 4)
}

fn is_combining(c: char) -> bool {
    ('\u{0300}'..='\u{036F}').contains(&c)
}

fn compose(base: char, mark: char) -> Option<char> {
    let (b, m) = (base as u32, mark as u32);
    if b > 0xFFFF || m > 0xFFFF {
        return None;
    }
    compose::COMPOSE
        .binary_search_by_key(&(b as u16, m as u16), |&(cb, cm, _)| (cb, cm))
        .ok()
        .and_then(|i| char::from_u32(compose::COMPOSE[i].2 as u32))
}

/// The characters of `text` as the face will look them up: a base letter followed by a combining
/// mark becomes its precomposed form when Latin has one; otherwise both pass through unchanged and
/// the mark draws as a missing glyph on its own.
pub fn chars(text: &str) -> impl Iterator<Item = char> + '_ {
    let mut it = text.chars().peekable();
    core::iter::from_fn(move || {
        let c = it.next()?;
        if let Some(&next) = it.peek() {
            if is_combining(next) {
                if let Some(composed) = compose(c, next) {
                    it.next();
                    return Some(composed);
                }
            }
        }
        Some(c)
    })
}

enum Glyph<'f> {
    Node(&'f Node),
    /// A one-pixel hollow box: visible, never a plausible wrong letter.
    Missing { w: i32, h: i32, adv: i32 },
}

impl Face {
    pub fn glyph(&self, c: char) -> Option<&Node> {
        let cp = c as u32;
        if cp > 0xFFFF {
            return None;
        }
        self.nodes
            .binary_search_by_key(&(cp as u16), |n| n.cp)
            .ok()
            .map(|i| &self.nodes[i])
    }

    /// Whether every character of `text` has a glyph, after composition.
    pub fn covers(&self, text: &str) -> bool {
        chars(text).all(|c| self.glyph(c).is_some())
    }

    /// Ascent plus descent: the rows one line of this face may touch.
    pub fn line_height(&self) -> i32 {
        self.ascent as i32 + self.descent as i32
    }

    fn lookup(&self, c: char) -> Glyph<'_> {
        match self.glyph(c) {
            Some(n) => Glyph::Node(n),
            None => {
                let px = self.px as i32;
                let w = (px * 3 / 5).max(3);
                Glyph::Missing { w, h: (px * 7 / 10).max(3), adv: w + (px / 10).max(1) }
            }
        }
    }

    pub fn measure(&self, text: &str) -> Measure {
        let mut m = Measure::default();
        let mut first = true;
        for c in chars(text) {
            let (left, right, adv) = match self.lookup(c) {
                Glyph::Node(n) => (n.left as i32, n.left as i32 + n.w as i32, n.adv as i32),
                Glyph::Missing { w, adv, .. } => {
                    m.missing = m.missing.saturating_add(1);
                    (0, w, adv)
                }
            };
            if right > left {
                let (l, r) = (m.advance + left, m.advance + right);
                if first {
                    m.ink_left = l;
                    m.ink_right = r;
                    first = false;
                } else {
                    m.ink_left = m.ink_left.min(l);
                    m.ink_right = m.ink_right.max(r);
                }
            }
            m.advance += adv;
        }
        m
    }

    fn level(&self, node: &Node, col: i32, row: i32) -> u8 {
        let i = node.off as usize * 4 + (row * node.w as i32 + col) as usize;
        (self.data[i / 4] >> (2 * (i % 4))) & 3
    }

    /// Draws `text` with its pen at `x` for `Left`, its advance centred on `x` for `Center`, or
    /// ending at `x` for `Right`, sitting on `baseline`, in `ink`. Returns what it measured.
    pub fn draw(&self, canvas: &mut Canvas, text: &str, x: i32, baseline: i32, align: Align, ink: u8) -> Measure {
        let m = self.measure(text);
        let mut pen = match align {
            Align::Left => x,
            Align::Center => x - m.advance / 2,
            Align::Right => x - m.advance,
        };
        for c in chars(text) {
            match self.lookup(c) {
                Glyph::Node(n) => {
                    let x0 = pen + n.left as i32;
                    let y0 = baseline - n.top as i32;
                    for row in 0..n.h as i32 {
                        for col in 0..n.w as i32 {
                            let level = self.level(n, col, row);
                            if level != 0 {
                                canvas.put(x0 + col, y0 + row, shade(ink, canvas.ground, level));
                            }
                        }
                    }
                    pen += n.adv as i32;
                }
                Glyph::Missing { w, h, adv } => {
                    let y0 = baseline - h;
                    for i in 0..w {
                        canvas.put(pen + i, y0, ink);
                        canvas.put(pen + i, baseline - 1, ink);
                    }
                    for j in 0..h {
                        canvas.put(pen, y0 + j, ink);
                        canvas.put(pen + w - 1, y0 + j, ink);
                    }
                    pen += adv;
                }
            }
        }
        m
    }

    /// [`Face::draw`] with the line's top at `top` instead of its baseline.
    pub fn draw_top(&self, canvas: &mut Canvas, text: &str, x: i32, top: i32, align: Align, ink: u8) -> Measure {
        self.draw(canvas, text, x, top + self.ascent as i32, align, ink)
    }

    /// Greedy word wrap against `max_width`, filling `lines` in order. Returns how many lines the
    /// whole text needs, which exceeds `lines.len()` when it did not fit; a word wider than the
    /// width sits alone on its line rather than being split.
    pub fn wrap<'t>(&self, text: &'t str, max_width: i32, lines: &mut [&'t str]) -> usize {
        let mut count = 0;
        let mut line_start = 0usize;
        let mut line_end = 0usize;
        let emit = |lines: &mut [&'t str], s: &'t str, count: &mut usize| {
            if s.is_empty() {
                return;
            }
            if *count < lines.len() {
                lines[*count] = s;
            }
            *count += 1;
        };
        let word_ends = text
            .char_indices()
            .filter(|&(_, c)| c == ' ')
            .map(|(i, _)| i)
            .chain(core::iter::once(text.len()));
        for word_end in word_ends {
            if word_end <= line_end {
                continue;
            }
            let candidate = text[line_start..word_end].trim();
            if self.measure(candidate).advance <= max_width || line_end == line_start {
                line_end = word_end;
            } else {
                emit(lines, text[line_start..line_end].trim(), &mut count);
                line_start = line_end + 1;
                line_end = word_end.max(line_start);
            }
        }
        if line_start < text.len() {
            emit(lines, text[line_start..].trim(), &mut count);
        }
        count
    }
}

/// The first of `faces` whose advance for `text` fits `max_width`: the size ladder.
pub fn pick<'f>(faces: &[&'f Face], text: &str, max_width: i32) -> Option<&'f Face> {
    faces.iter().copied().find(|f| f.measure(text).advance <= max_width)
}

#[cfg(test)]
mod tests {
    use super::faces::*;
    use super::*;

    const W: u32 = 240;
    const H: u32 = 240;

    fn all_faces() -> Vec<(&'static str, &'static Face)> {
        vec![
            ("SEMIBOLD_18_ASCII", &SEMIBOLD_18_ASCII),
            ("REGULAR_14_ASCII", &REGULAR_14_ASCII),
            ("REGULAR_12_ASCII", &REGULAR_12_ASCII),
            ("SEMIBOLD_20_ASCII", &SEMIBOLD_20_ASCII),
            ("REGULAR_18_LATIN", &REGULAR_18_LATIN),
            ("REGULAR_16_LATIN", &REGULAR_16_LATIN),
            ("SEMIBOLD_24_ANSWERS", &SEMIBOLD_24_ANSWERS),
            ("SEMIBOLD_32_TITLE", &SEMIBOLD_32_TITLE),
            ("SEMIBOLD_27_CLOCK", &SEMIBOLD_27_CLOCK),
            ("SEMIBOLD_36_CLOCK", &SEMIBOLD_36_CLOCK),
            ("SEMIBOLD_49_CLOCK", &SEMIBOLD_49_CLOCK),
            ("SEMIBOLD_60_CLOCK", &SEMIBOLD_60_CLOCK),
        ]
    }

    #[test]
    fn every_face_is_well_formed() {
        for (name, f) in all_faces() {
            assert!(f.nodes.windows(2).all(|p| p[0].cp < p[1].cp), "{name}: nodes not sorted by code point");
            for n in f.nodes {
                let bits = n.w as usize * n.h as usize * 2;
                assert!(n.off as usize + bits.div_ceil(8) <= f.data.len(), "{name}: U+{:04X} runs past the bitstream", n.cp);
                assert!(n.h as i32 <= f.line_height() + 2, "{name}: U+{:04X} taller than the line", n.cp);
            }
            assert!(f.glyph(' ').is_some(), "{name}: no space");
        }
    }

    /// Barcode's README measured these with TouchGFX's own `getStringWidth` on the faces it shipped.
    #[test]
    fn advances_match_the_touchgfx_build_barcode_measured() {
        assert_eq!(SEMIBOLD_20_ASCII.measure("0123456789ABC").advance, 172);
        assert_eq!(SEMIBOLD_20_ASCII.measure("0123456789ABCD").advance, 186);
        assert_eq!(SEMIBOLD_20_ASCII.measure("0123456789ABCDE").advance, 197);
        assert_eq!(SEMIBOLD_20_ASCII.measure("0123456789ABCDEF").advance, 208);
        assert_eq!(SEMIBOLD_20_ASCII.measure("GYMWORLD12345678").advance, 222);
        assert_eq!(SEMIBOLD_20_ASCII.measure("WWWWWWWWWWWW").advance, 240);
        assert_eq!(REGULAR_18_LATIN.measure("0123456789ABCD").advance, 160);
        assert_eq!(REGULAR_18_LATIN.measure("0123456789ABCDEF").advance, 178);
        assert_eq!(REGULAR_18_LATIN.measure("GYMWORLD12345678").advance, 193);
        assert_eq!(REGULAR_18_LATIN.measure("WWWWWWWWWWWW").advance, 216);
    }

    #[test]
    fn latin_faces_cover_tier_one_and_ascii_faces_do_not() {
        assert!(REGULAR_18_LATIN.covers("José Zoë Müller Søren Łukasz ° µ ± … – — “ ” €"));
        assert!(!SEMIBOLD_20_ASCII.covers("é"));
        assert!(!REGULAR_18_LATIN.covers("′"), "Poppins has no prime");
    }

    #[test]
    fn a_decomposed_accent_is_composed_before_lookup() {
        let composed: Vec<char> = chars("Jose\u{0301}").collect();
        assert_eq!(composed, vec!['J', 'o', 's', 'é']);
        assert!(REGULAR_18_LATIN.covers("Jose\u{0301}"));
        assert_eq!(REGULAR_18_LATIN.measure("Jose\u{0301}"), REGULAR_18_LATIN.measure("José"));
    }

    #[test]
    fn a_missing_glyph_is_counted_and_drawn_as_a_box() {
        let m = SEMIBOLD_20_ASCII.measure("aé");
        assert_eq!(m.missing, 1);
        let mut buf = vec![0u8; (W * H) as usize];
        let mut c = Canvas::rect(&mut buf, W, H);
        SEMIBOLD_20_ASCII.draw(&mut c, "é", 100, 100, Align::Left, WHITE);
        let lit = buf.iter().filter(|&&b| b != 0).count();
        assert!(lit > 20 && lit < 80, "a hollow box, not a filled one or nothing: {lit} lit");
        assert_eq!(buf[(99 * 240 + 100) as usize], WHITE, "box corner at the pen, on the baseline's row above");
    }

    #[test]
    fn alignment_places_the_advance_where_it_says() {
        let text = "0123456789ABCD";
        let adv = SEMIBOLD_20_ASCII.measure(text).advance;
        for (align, x, expected_left_pen) in [(Align::Left, 30, 30), (Align::Center, 120, 120 - adv / 2), (Align::Right, 200, 200 - adv)] {
            let mut buf = vec![0u8; (W * H) as usize];
            let mut c = Canvas::rect(&mut buf, W, H);
            let m = SEMIBOLD_20_ASCII.draw(&mut c, text, x, 120, align, WHITE);
            let first_lit_col = (0..240).find(|&x| (0..240).any(|y| buf[(y * 240 + x) as usize] != 0)).unwrap();
            assert_eq!(first_lit_col as i32, expected_left_pen + m.ink_left, "{align:?}");
        }
    }

    #[test]
    fn nothing_is_lit_outside_the_disc() {
        let mut buf = vec![0u8; (W * H) as usize];
        let mut c = Canvas::round(&mut buf, W, H);
        for y in [10, 30, 120, 210, 230] {
            SEMIBOLD_20_ASCII.draw(&mut c, "WWWWWWWWWWWWWWWWWWWWWWWW", 120, y, Align::Center, WHITE);
        }
        for y in 0..240i32 {
            for x in 0..240i32 {
                let lit = (2 * x - 239).pow(2) + (2 * y - 239).pow(2) <= 239 * 239;
                if !lit {
                    assert_eq!(buf[(y * 240 + x) as usize], 0, "({x},{y}) is behind the bezel");
                }
            }
        }
        assert!(buf.iter().any(|&b| b != 0));
    }

    #[test]
    fn shading_is_the_apps_own_rule_over_black_and_blends_toward_a_ground() {
        assert_eq!(shade(WHITE, BLACK, 3), 0xFF);
        assert_eq!(shade(WHITE, BLACK, 2), 0xC0 | 0b10_10_10);
        assert_eq!(shade(WHITE, BLACK, 1), 0xC0 | 0b01_01_01);
        let dim = 0xC0 | 0b10_10_10;
        assert_eq!(shade(dim, BLACK, 1), 0xC0 | 0b01_01_01);
        assert_eq!(shade(BLACK, WHITE, 3), BLACK);
        assert_eq!(shade(BLACK, WHITE, 1), 0xC0 | 0b10_10_10);
    }

    #[test]
    fn drawn_text_uses_all_four_levels() {
        let mut buf = vec![0u8; (W * H) as usize];
        let mut c = Canvas::rect(&mut buf, W, H);
        REGULAR_18_LATIN.draw(&mut c, "Set it to Code128,", 120, 120, Align::Center, WHITE);
        for level in 1..=3u8 {
            let colour = shade(WHITE, BLACK, level);
            assert!(buf.contains(&colour), "level {level} never drawn");
        }
    }

    #[test]
    fn wrap_never_exceeds_the_width_never_splits_a_word_and_loses_nothing() {
        let text = "No codes yet. Set one in the UNA app, or write input.json.";
        let mut lines = [""; 4];
        let n = REGULAR_18_LATIN.wrap(text, 200, &mut lines);
        assert!(n <= 4, "needs {n} lines");
        let mut words = Vec::new();
        for line in &lines[..n] {
            assert!(REGULAR_18_LATIN.measure(line).advance <= 200, "{line:?} too wide");
            words.extend(line.split(' '));
        }
        assert_eq!(words, text.split(' ').collect::<Vec<_>>());
    }

    #[test]
    fn wrap_reports_overflow_instead_of_dropping_lines() {
        let text = "one two three four five six seven eight nine ten eleven twelve";
        let mut lines = [""; 2];
        let n = REGULAR_18_LATIN.wrap(text, 60, &mut lines);
        assert!(n > 2);
        assert_eq!(lines[0], "one");
    }

    #[test]
    fn a_word_wider_than_the_box_sits_alone_rather_than_being_split() {
        let mut lines = [""; 3];
        let n = REGULAR_18_LATIN.wrap("a WWWWWWWWWWWWWWWWWWWW b", 60, &mut lines);
        assert_eq!(n, 3);
        assert_eq!(lines[1], "WWWWWWWWWWWWWWWWWWWW");
    }

    #[test]
    fn pick_walks_the_ladder() {
        let ladder = [&SEMIBOLD_20_ASCII, &REGULAR_18_LATIN];
        assert!(core::ptr::eq(pick(&ladder, "0123456789ABCD", 187).unwrap(), &SEMIBOLD_20_ASCII));
        assert!(core::ptr::eq(pick(&ladder, "0123456789ABCDE", 187).unwrap(), &REGULAR_18_LATIN));
        assert!(pick(&ladder, "GYMWORLD12345678", 187).is_none());
    }

    #[test]
    fn draw_top_puts_the_ascent_above_the_top() {
        let mut buf = vec![0u8; (W * H) as usize];
        let mut c = Canvas::rect(&mut buf, W, H);
        SEMIBOLD_20_ASCII.draw_top(&mut c, "H", 20, 50, Align::Left, WHITE);
        let first_row = (0..240).find(|&y| (0..240).any(|x| buf[(y * 240 + x) as usize] != 0)).unwrap();
        assert!(first_row >= 50 && first_row < 50 + SEMIBOLD_20_ASCII.ascent as usize);
    }
}
