"""Build-time atlas generator for candidate B: FreeType light autohint, 8-bit coverage, quantised to
four levels at (1/6, 1/2, 5/6), packed 2bpp row-major bitstream, one 12-byte node per glyph. Emits a
Rust source with `static` tables. Deterministic for a pinned FreeType."""
import freetype, math, sys, numpy as np
S = "/private/tmp/claude-501/-Users-tobymurray-git-watch-apps/6371c74a-dd42-4862-98e7-6fdff05b7008/scratchpad/fonts/"
def build(name, path, px, cps):
    f = freetype.Face(S + path); f.set_pixel_sizes(0, px)
    nodes = []; data = bytearray(); bits = []
    for cp in cps:
        gi = f.get_char_index(cp)
        if gi == 0 and cp != 0x20: continue
        f.load_glyph(gi, freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_LIGHT)
        g = f.glyph; b = g.bitmap
        cov = np.frombuffer(bytes(b.buffer), dtype=np.uint8).reshape(b.rows, b.pitch)[:, :b.width] / 255.0 if b.rows else np.zeros((0, 0))
        lv = np.zeros(cov.shape, dtype=np.uint8)
        for i, t in enumerate((1/6, 1/2, 5/6)): lv[cov >= t] = i + 1
        off = len(data)
        acc = 0; n = 0
        for v in lv.flatten():
            acc |= int(v) << (2 * (n % 4)); n += 1
            if n % 4 == 0: data.append(acc); acc = 0
        if n % 4: data.append(acc)
        nodes.append((cp, b.width, b.rows, g.bitmap_top, g.bitmap_left, g.advance.x // 64, off))
    asc = math.ceil(f.size.ascender / 64); desc = math.ceil(-f.size.descender / 64)
    out = [f"pub static {name}: Face = Face {{ px: {px}, ascent: {asc}, descent: {desc}, nodes: &{name}_NODES, data: &{name}_DATA }};"]
    out.append(f"static {name}_NODES: [Node; {len(nodes)}] = [")
    for cp, w, h, top, left, adv, off in nodes:
        out.append(f"    Node {{ off: {off}, cp: {cp}, w: {w}, h: {h}, top: {top}, left: {left}, adv: {adv}, _pad: 0 }},")
    out.append("];")
    out.append(f"static {name}_DATA: [u8; {len(data)}] = [" + ",".join(str(x) for x in data) + "];")
    print(f"{name}: {len(nodes)} glyphs, {len(data)} glyph bytes, {len(nodes)*12} node bytes", file=sys.stderr)
    return "\n".join(out)
ascii_cps = list(range(0x20, 0x7F))
t1 = sorted(set(ascii_cps + list(range(0xA0, 0x180)) + [0x2026, 0x2013, 0x2014, 0x2018, 0x2019, 0x201C, 0x201D, 0x20AC, 0x2022]))
src = ["// generated by gen_atlas.py", "use crate::{Face, Node};",
       build("REGULAR_18", "Poppins-Regular.ttf", 18, t1), build("SEMIBOLD_20", "Poppins-SemiBold.ttf", 20, ascii_cps), build("SEMIBOLD_54", "Poppins-SemiBold.ttf", 54, [ord(c) for c in "0123456789:"])]
open("proto_b_atlas/src/atlas.rs", "w").write("\n".join(src) + "\n")
