[package]
name = "panicprobe"
version = "0.0.0"
edition = "2021"

[features]
default = []
literal = []
location = []
full = []
location_min = []

[dependencies]
panelkit = { path = "../../..", default-features = false, features = ["round"] }

[profile.release]
panic = "abort"
opt-level = "z"
lto = true
codegen-units = 1
overflow-checks = false
