#!/usr/bin/env python3
"""Turns the faces in faces.json into src/faces.rs, and the composition table into src/compose.rs.

Rasterization is FreeType's light autohinter, coverage rounded to the nearest third, blank edge
rows and columns cropped. Those three choices reproduce the 2bpp Poppins glyphs TouchGFX shipped
pixel for pixel (Docs/TEXT.md, "What this corrects in the record"); change any of them and the
oracle test in tests/oracle/touchgfx.rs says so.

    python3 Tools/atlas.py            # rewrite src/faces.rs and src/compose.rs
    python3 Tools/atlas.py --check    # exit 1 if a rewrite would change either file
"""
import json, math, os, sys, unicodedata
import freetype
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
FONTS = os.path.join(ROOT, "Fonts")

ASCII = list(range(0x20, 0x7F))
LATIN = sorted(set(ASCII + list(range(0xA0, 0x180))
                   + [0x2026, 0x2013, 0x2014, 0x2018, 0x2019, 0x201C, 0x201D, 0x20AC, 0x2022]))
CHARSETS = {"ascii": ASCII, "latin": LATIN}

LEVEL_THRESHOLDS = (43, 128, 213)  # round(v * 3 / 255) for v in 0..=255


def charset(spec):
    if spec in CHARSETS:
        return CHARSETS[spec]
    return sorted(set([0x20] + [ord(c) for c in spec]))


def quantise(cov):
    lv = np.zeros(cov.shape, dtype=np.uint8)
    for i, t in enumerate(LEVEL_THRESHOLDS):
        lv[cov >= t] = i + 1
    return lv


def crop(lv):
    ys, xs = np.nonzero(lv)
    if len(ys) == 0:
        return lv[:0, :0], 0, 0
    return lv[ys.min():ys.max() + 1, xs.min():xs.max() + 1], int(ys.min()), int(xs.min())


def pack(lv):
    out = bytearray()
    acc = 0
    n = 0
    for v in lv.flatten():
        acc |= int(v) << (2 * (n % 4))
        n += 1
        if n % 4 == 0:
            out.append(acc)
            acc = 0
    if n % 4:
        out.append(acc)
    return bytes(out)


def build_face(entry):
    face = freetype.Face(os.path.join(FONTS, entry["font"]))
    face.set_pixel_sizes(0, entry["px"])
    nodes = []
    data = bytearray()
    for cp in charset(entry["charset"]):
        gi = face.get_char_index(cp)
        if gi == 0 and cp != 0x20:
            continue
        face.load_glyph(gi, freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_LIGHT)
        g = face.glyph
        b = g.bitmap
        if b.rows and b.width:
            cov = np.frombuffer(bytes(b.buffer), dtype=np.uint8).reshape(b.rows, b.pitch)[:, :b.width]
            lv, dy, dx = crop(quantise(cov))
        else:
            lv, dy, dx = np.zeros((0, 0), dtype=np.uint8), 0, 0
        h, w = lv.shape
        top = g.bitmap_top - dy
        left = g.bitmap_left + dx
        adv = g.advance.x // 64
        for value, limit, what in [(w, 255, "width"), (h, 255, "height"), (adv, 255, "advance")]:
            if value > limit:
                sys.exit(f"{entry['name']} U+{cp:04X}: {what} {value} does not fit a byte")
        if not -128 <= top <= 127 or not -128 <= left <= 127:
            sys.exit(f"{entry['name']} U+{cp:04X}: bearing out of range")
        nodes.append((len(data), cp, w, h, top, left, adv))
        data += pack(lv)
    ascent = math.ceil(face.size.ascender / 64)
    descent = math.ceil(-face.size.descender / 64)
    return nodes, bytes(data), ascent, descent


def rust_face(entry, nodes, data, ascent, descent):
    name = entry["name"]
    lines = [f"/// {entry['font']} at {entry['px']} px, charset `{entry['charset']}`: {len(nodes)} glyphs, {len(data)} glyph bytes.",
             f"pub static {name}: Face = Face {{ px: {entry['px']}, ascent: {ascent}, descent: {descent}, flags: 0, nodes: &{name}_NODES, data: &{name}_DATA }};",
             f"static {name}_NODES: [Node; {len(nodes)}] = ["]
    for off, cp, w, h, top, left, adv in nodes:
        lines.append(f"    Node {{ off: {off}, cp: 0x{cp:04X}, w: {w}, h: {h}, top: {top}, left: {left}, adv: {adv}, flags: 0 }},")
    lines.append("];")
    body = ",".join(str(x) for x in data)
    lines.append(f"static {name}_DATA: [u8; {len(data)}] = [{body}];")
    return "\n".join(lines)


def compose_table():
    """(base, combining mark) pairs whose canonical composition is a code point in `latin`."""
    rows = []
    for cp in LATIN:
        nfd = unicodedata.normalize("NFD", chr(cp))
        if len(nfd) == 2 and unicodedata.combining(nfd[1]):
            rows.append((ord(nfd[0]), ord(nfd[1]), cp))
    rows.sort()
    return rows


def generate():
    manifest = json.load(open(os.path.join(HERE, "faces.json")))
    ft = ".".join(str(x) for x in freetype.version())
    header = (f"// Generated by Tools/atlas.py from Tools/faces.json with FreeType {ft}. Do not edit;\n"
              f"// rerun the tool. Format: Docs/TEXT.md \"The format\"; oracle: tests/oracle/touchgfx.rs.\n"
              f"use crate::{{Face, Node}};\n")
    parts = [header]
    for entry in manifest["faces"]:
        nodes, data, ascent, descent = build_face(entry)
        parts.append(rust_face(entry, nodes, data, ascent, descent))
        print(f"{entry['name']:22s} {len(nodes):3d} glyphs {len(data):6d} glyph bytes {len(nodes) * 12:5d} node bytes", file=sys.stderr)
    faces_rs = "\n\n".join(parts) + "\n"
    rows = compose_table()
    compose_rs = ("// Generated by Tools/atlas.py. (base, combining mark, composed) for every `latin` code point\n"
                  "// whose NFD is a base letter plus one mark; sorted by (base, mark) for a binary search.\n"
                  f"pub static COMPOSE: [(u16, u16, u16); {len(rows)}] = [\n"
                  + "\n".join(f"    (0x{b:04X}, 0x{m:04X}, 0x{c:04X})," for b, m, c in rows) + "\n];\n")
    return {"src/faces.rs": faces_rs, "src/compose.rs": compose_rs}


def main():
    out = generate()
    check = "--check" in sys.argv
    changed = False
    for rel, text in out.items():
        path = os.path.join(ROOT, rel)
        current = open(path).read() if os.path.exists(path) else None
        if current != text:
            changed = True
            if check:
                print(f"{rel} is stale", file=sys.stderr)
            else:
                open(path, "w").write(text)
                print(f"wrote {rel}", file=sys.stderr)
    if check and changed:
        sys.exit(1)


if __name__ == "__main__":
    main()
