#!/usr/bin/env python3
"""Extracts a few glyphs from the 2bpp Poppins tables TouchGFX generated for Squash into
tests/oracle/touchgfx.rs, so the crate can prove its atlases match what the wearer saw.

    python3 Tools/touchgfx_oracle.py
"""
import os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SQUASH = os.path.join(ROOT, "..", "Squash", "Software", "Apps", "TouchGFX-GUI", "generated", "fonts", "src")

# (TouchGFX face, TextKit face, sample glyphs)
FACES = [
    ("SemiBold_18", "SEMIBOLD_18_ASCII", "NOTIFICATIONS?"),
    ("Regular_14", "REGULAR_14_ASCII", "R1TOGGLEBACK"),
    ("SemiBold_20", "SEMIBOLD_20_ASCII", "0123456789ABCDW"),
    ("Regular_18", "REGULAR_18_LATIN", "GYMWORLD12345678abcdefghijklmnopqrstuvwxyz.,"),
]


def hexbytes(path):
    src = "\n".join(l for l in open(path).read().splitlines() if not l.strip().startswith("//"))
    return bytes(int(x, 16) for x in re.findall(r"0x([0-9A-Fa-f]{2})", src))


def table(name):
    text = open(os.path.join(SQUASH, f"Table_Poppins_{name}_2bpp.cpp")).read()
    rows = re.findall(r"\{\s*(\d+),\s*0x([0-9A-F]+),\s*(\d+),\s*(\d+),\s*(\d+),\s*(-?\d+),\s*(\d+),", text)
    return {int(u, 16): (int(o), int(w), int(h), int(t), int(l), int(a)) for o, u, w, h, t, l, a in rows}


def unpack(data, off, w, h):
    out = []
    bit = off * 8
    for _ in range(w * h):
        out.append((data[bit // 8] >> (bit % 8)) & 3)
        bit += 2
    return out


def main():
    lines = ["// Generated by Tools/touchgfx_oracle.py from Squash's TouchGFX font tables. Do not edit.",
             "//! Glyphs as TouchGFX Designer rasterized them for this panel: the bar every atlas is held to.",
             "",
             "/// One TouchGFX glyph: code point, width, height, top, left, advance, and its pixels as levels 0..=3, row-major.",
             "pub struct Oracle { pub cp: u32, pub w: u8, pub h: u8, pub top: i8, pub left: i8, pub adv: u8, pub levels: &'static [u8] }",
             ""]
    for tg, tk, sample in FACES:
        data = hexbytes(os.path.join(SQUASH, f"Font_Poppins_{tg}_2bpp_0.cpp"))
        rows = table(tg)
        lines.append(f"/// TouchGFX `Font_Poppins_{tg}_2bpp` against TextKit `{tk}`.")
        lines.append(f"pub static {tk}: &[Oracle] = &[")
        for ch in dict.fromkeys(sample):
            off, w, h, t, l, a = rows[ord(ch)]
            levels = ",".join(str(v) for v in unpack(data, off, w, h))
            lines.append(f"    Oracle {{ cp: 0x{ord(ch):04X}, w: {w}, h: {h}, top: {t}, left: {l}, adv: {a}, levels: &[{levels}] }},")
        lines.append("];")
        lines.append("")
    path = os.path.join(ROOT, "tests", "oracle", "touchgfx.rs")
    open(path, "w").write("\n".join(lines))
    print(f"wrote {path}", file=sys.stderr)


if __name__ == "__main__":
    main()
