/**
 ******************************************************************************
 * @file    DmaPwm.hpp
 * @brief   The same waveform, generated by hardware, with the CPU asleep.
 ******************************************************************************
 *
 * `SoftPwm` proves the light dims. It also demonstrates why nobody should ship
 * that technique: it spins a thread, it starves the GUI, and it costs more
 * battery in CPU than it saves in LED. This is the production shape of the same
 * thing.
 *
 * A basic timer's update event drives a GPDMA channel that copies one word at a
 * time from a RAM buffer into `GPIOF BSRR`. The buffer holds the waveform: each
 * word is either bit-reset 3 (light on) or bit-set 3 (light off), and the duty
 * is how many of them are which. Once started, **no code runs at all**. No
 * interrupt, no polling, no CPU per edge.
 *
 * That last point is what makes it possible from an application rather than only
 * from the kernel. An app cannot install an interrupt handler, because `VTOR`
 * belongs to the kernel. It does not need to: a circular DMA has nothing to
 * service.
 *
 * ## Why PF3 works despite having no timer output
 *
 * It does not need one. The timer never reaches a pin; it only produces an
 * update event, and the DMA does the writing. `BSRR` does not care who wrote it.
 * That is the whole trick, and it is why this technique fits a pin that ST's
 * alternate-function table offers nothing useful for.
 *
 * ## Block-repeat rather than a linked list
 *
 * GPDMA's usual way to loop is a linked-list node in RAM pointing at itself.
 * Block-repeat mode does the same job with no node: one block of `BNDT` bytes
 * repeated `BRC + 1` times, with `BRSAO` rewinding the source to the start of
 * the buffer at each repeat. Fewer registers, no memory node, no alignment rule
 * to get wrong blind.
 *
 * `BRC` is 11 bits, so the transfer stops after at most 2048 blocks and has to be
 * re-armed. At the sizes here that is roughly every ten seconds, and re-arming
 * is one register write.
 *
 * ## This is the riskiest code in the app, and it is gated accordingly
 *
 * `SoftPwm` only ever wrote `BSRR`: write-only, self-clearing, nothing to
 * restore, and the worst a crash could do was leave the light in a state the
 * kernel already uses.
 *
 * This writes a clock enable, timer configuration, and a DMA channel **whose
 * destination address is under our control**. A wrong destination would have the
 * DMA engine writing into memory rather than into a peripheral.
 *
 * So `start()` configures everything with the channel disabled, then reads back
 * every register it wrote and compares it against what it intended. `CDAR` in
 * particular must read exactly `GPIOF BSRR`. Any mismatch aborts and enables
 * nothing. The gate turns "a wrong address corrupts memory" into "a wrong
 * address stops the app", which is the difference between a bug and an incident.
 *
 * Every register is saved before it is touched and restored by `stop()`,
 * including the clock-enable bits, so a run leaves the machine as it found it.
 *
 ******************************************************************************
 */

#ifndef DMA_PWM_HPP
#define DMA_PWM_HPP

#include <cstddef>
#include <cstdint>

namespace Pwm
{

/// Why a start attempt did not produce a waveform.
enum class DmaStatus : uint8_t {
    Idle           = 0, ///< Never started.
    Running        = 1, ///< Configured, verified and enabled.
    NoRegisters    = 2, ///< Host or simulator build.
    NoFreeTimer    = 3, ///< Every candidate timer's clock is already on.
    NoFreeChannel  = 4, ///< No GPDMA channel is idle.
    VerifyFailed   = 5, ///< A register did not read back as written. Nothing enabled.
    NoTimerClock   = 6, ///< The waveform did not advance, so its rate is unknown.
};

/**
 * @brief How the thread passes time it is not using.
 *
 * This is the whole question. A run at the right divider measured 255 Hz with
 * the core spinning and 27 Hz across a kernel sleep, so the timer or the DMA is
 * being gated off with the core, and no divider fixes that: what reaches the eye
 * is the light frozen at whatever the last word wrote, for as long as the core
 * stays down.
 *
 * The two sleeps are separated because they need not behave alike. A kernel may
 * take a long wait as licence to stop the clocks and a one-millisecond wait as
 * something to idle through, and if so the difference between them is the
 * difference between a dimmed light and a strobing one.
 */
enum class Idle : uint8_t {
    Spin      = 0, ///< Never gives the core up. The hardware's own rate.
    Yield     = 1, ///< Hands back the slice, repeatedly.
    ShortNaps = 2, ///< A run of one-millisecond sleeps.
    LongSleep = 3, ///< One sleep for the whole window.
};

const char* idleName(Idle i);

constexpr size_t kIdleModes = 4;

/**
 * @brief What the waveform actually did, measured rather than computed.
 *
 * One rate per way of being idle. If they all agree, the waveform is genuinely
 * autonomous and the CPU can be given away. Wherever a mode's rate falls below
 * the spinning one, that mode stops the waveform for the difference.
 */
struct DmaRates {
    uint32_t arr = 0; ///< The divider these rates were measured at.
    uint32_t hz[kIdleModes] = {0, 0, 0, 0};

    uint32_t spin() const { return hz[static_cast<size_t>(Idle::Spin)]; }
};

const char* dmaStatusName(DmaStatus s);

/**
 * @brief Waveform resolution, in words.
 *
 * Each word is one DMA transfer and one timer tick. 128 gives a duty step of
 * 0.78 percent, comfortably finer than the twelve levels the discrimination run
 * showed to be distinguishable, for 512 bytes of RAM.
 */
constexpr size_t kWaveWords = 128;

/// The divider is 16 bits on a basic timer.
constexpr uint32_t kArrMax = 0xFFFFu;

/**
 * @brief The new divider that turns a measured rate into the wanted one.
 *
 * Rate is inversely proportional to the divider, so this is one multiply. It is
 * a free function rather than a private method because it is the arithmetic that
 * has been wrong twice, in two different ways, and it is the only part of this
 * file that can be tested without the registers.
 *
 * Clamped at both ends: below 1 the timer would free-run, above 65535 the value
 * does not fit. A measurement of zero leaves the divider alone rather than
 * dividing by it.
 */
constexpr uint32_t trimmedArr(uint32_t arr, uint32_t measuredHz, uint32_t targetHz)
{
    if (measuredHz == 0u || targetHz == 0u || arr == 0u) {
        return arr;
    }
    const uint64_t scaled = (static_cast<uint64_t>(arr) * measuredHz) / targetHz;
    if (scaled < 1u) {
        return 1u;
    }
    if (scaled > kArrMax) {
        return kArrMax;
    }
    return static_cast<uint32_t>(scaled);
}

/**
 * @brief Whether an idle mode's rate is close enough to the spinning one to use.
 *
 * Ten percent. The rate is counted passes over a window, so it carries a pass or
 * two of quantisation, and a mode that is genuinely not gated will sit within
 * that. A mode that stops the clocks does not come close: the one measurement of
 * this so far was 27 against 255, which is off by a factor of nine, not by a
 * counting error.
 */
constexpr bool keepsUp(uint32_t modeHz, uint32_t spinHz)
{
    if (spinHz == 0u) {
        return false;
    }
    return modeHz >= spinHz - (spinHz / 10u);
}

class DmaPwm
{
public:
    /**
     * @brief Claim a timer and a DMA channel, build the waveform, verify, enable.
     * @param dutyPercent 0 to 100.
     * @param periodUs    Length of one full waveform pass.
     * @param sleepMs     Hands the CPU back, for the asleep-rate comparison.
     * @param nowMs       Wall clock, for timing the measurement windows.
     * @return Running on success. Anything else means nothing was enabled.
     *
     * The divider is trimmed against a measurement of the waveform's own rate
     * rather than computed from an assumed clock. Two earlier versions computed
     * it: one assumed the timer ran at the core clock and landed at about 5 Hz,
     * the other measured the timer's input clock and landed at about 10 Hz. The
     * output is the only thing worth measuring, and the DMA counts its own
     * passes in hardware, so it is measurable without a camera.
     */
    DmaStatus start(uint8_t dutyPercent, uint32_t periodUs, void (*sleepMs)(uint32_t),
                    uint32_t (*nowMs)(), void (*yieldNow)());

    /// Change duty with the hardware still running. Rewrites the buffer only;
    /// the DMA is reading it continuously, so the change takes effect within one
    /// pass and costs one pass of memory writes and no reconfiguration.
    void setDuty(uint8_t dutyPercent);

    /// Re-arm the block-repeat counter before it expires. Cheap, and the only
    /// thing the CPU has to do while a waveform is running.
    void poll();

    /// Disable, wait for idle, restore every saved register, including clocks.
    void stop();

    DmaStatus status() const { return mStatus; }
    uint8_t   duty() const { return mDuty; }

    /// Which timer and channel were borrowed, for the record.
    uint8_t timerIndex() const { return mTimerIndex; }
    uint8_t channelIndex() const { return mChannel; }

    /// How many times the block-repeat counter has been re-armed.
    uint32_t rearms() const { return mRearms; }

    /// The waveform's measured rate after trimming, spinning, in Hz. This is the
    /// number that decides whether the light dims or blinks.
    uint32_t waveHz() const { return mFinal.spin(); }

    /// The cheapest way of being idle that does not slow the waveform down.
    /// Spin if nothing else keeps up, which is a finding rather than a fix.
    Idle bestIdle() const { return mBestIdle; }

    /// Rates from the first probe, before the divider was trimmed. Kept because
    /// the awake-against-asleep comparison is a finding in its own right.
    const DmaRates& firstProbe() const { return mFirst; }
    const DmaRates& finalProbe() const { return mFinal; }

private:
    DmaStatus mStatus     = DmaStatus::Idle;
    uint8_t   mDuty       = 0;
    uint8_t   mTimerIndex = 0;   ///< 6 or 7.
    uint8_t   mChannel    = 0xFF;

    uint32_t mRearms   = 0;
    uint32_t mArr      = 0;
    Idle     mBestIdle = Idle::Spin;
    DmaRates mFirst;
    DmaRates mFinal;

    /// Saved before anything is written, restored by stop().
    uint32_t mSavedAhb1Enr  = 0;
    uint32_t mSavedApb1Enr1 = 0;
    bool     mTouchedClocks = false;
    bool     mConfigured    = false;

    bool pickTimer();

    /// Counts completed waveform passes over a wall-clock window, using the
    /// block-repeat counter the DMA maintains in hardware. `busy` spins for the
    /// window instead of sleeping through it, which is what separates the
    /// hardware's own rate from the rate a sleeping CPU leaves it running at.
    uint32_t measureHz(Idle idle, uint32_t windowMs, void (*sleepMs)(uint32_t),
                       uint32_t (*nowMs)(), void (*yieldNow)());

    /// Reload the block-repeat counter to full, so a measurement starts from a
    /// known count and cannot run it out mid-window.
    void rearm();

    void setArr(uint32_t arr);
    bool pickChannel();
    void buildWave(uint8_t dutyPercent);

    /// Reads back every register written and compares. False aborts the start.
    bool verify(uint32_t periodUs) const;
};

} // namespace Pwm

#endif // DMA_PWM_HPP
