/**
 ******************************************************************************
 * @file    DmaPwm.hpp
 * @brief   The same waveform, generated by hardware, with the CPU asleep.
 ******************************************************************************
 *
 * `SoftPwm` proves the light dims. It also demonstrates why nobody should ship
 * that technique: it spins a thread, it starves the GUI, and it costs more
 * battery in CPU than it saves in LED. This is the production shape of the same
 * thing.
 *
 * A basic timer's update event drives a GPDMA channel that copies one word at a
 * time from a RAM buffer into `GPIOF BSRR`. The buffer holds the waveform: each
 * word is either bit-reset 3 (light on) or bit-set 3 (light off), and the duty
 * is how many of them are which. Once started, **no code runs at all**. No
 * interrupt, no polling, no CPU per edge.
 *
 * That last point is what makes it possible from an application rather than only
 * from the kernel. An app cannot install an interrupt handler, because `VTOR`
 * belongs to the kernel. It does not need to: a circular DMA has nothing to
 * service.
 *
 * ## Why PF3 works despite having no timer output
 *
 * It does not need one. The timer never reaches a pin; it only produces an
 * update event, and the DMA does the writing. `BSRR` does not care who wrote it.
 * That is the whole trick, and it is why this technique fits a pin that ST's
 * alternate-function table offers nothing useful for.
 *
 * ## Block-repeat rather than a linked list
 *
 * GPDMA's usual way to loop is a linked-list node in RAM pointing at itself.
 * Block-repeat mode does the same job with no node: one block of `BNDT` bytes
 * repeated `BRC + 1` times, with `BRSAO` rewinding the source to the start of
 * the buffer at each repeat. Fewer registers, no memory node, no alignment rule
 * to get wrong blind.
 *
 * `BRC` is 11 bits, so the transfer stops after at most 2048 blocks and has to be
 * re-armed. At the sizes here that is roughly every ten seconds, and re-arming
 * is one register write.
 *
 * ## This is the riskiest code in the app, and it is gated accordingly
 *
 * `SoftPwm` only ever wrote `BSRR`: write-only, self-clearing, nothing to
 * restore, and the worst a crash could do was leave the light in a state the
 * kernel already uses.
 *
 * This writes a clock enable, timer configuration, and a DMA channel **whose
 * destination address is under our control**. A wrong destination would have the
 * DMA engine writing into memory rather than into a peripheral.
 *
 * So `start()` configures everything with the channel disabled, then reads back
 * every register it wrote and compares it against what it intended. `CDAR` in
 * particular must read exactly `GPIOF BSRR`. Any mismatch aborts and enables
 * nothing. The gate turns "a wrong address corrupts memory" into "a wrong
 * address stops the app", which is the difference between a bug and an incident.
 *
 * Every register is saved before it is touched and restored by `stop()`,
 * including the clock-enable bits, so a run leaves the machine as it found it.
 *
 ******************************************************************************
 */

#ifndef DMA_PWM_HPP
#define DMA_PWM_HPP

#include <cstddef>
#include <cstdint>

namespace Pwm
{

/// Why a start attempt did not produce a waveform.
enum class DmaStatus : uint8_t {
    Idle           = 0, ///< Never started.
    Running        = 1, ///< Configured, verified and enabled.
    NoRegisters    = 2, ///< Host or simulator build.
    NoFreeTimer    = 3, ///< Every candidate timer's clock is already on.
    NoFreeChannel  = 4, ///< No GPDMA channel is idle.
    VerifyFailed   = 5, ///< A register did not read back as written. Nothing enabled.
    NoTimerClock   = 6, ///< The timer would not count, so its rate is unknown.
};

const char* dmaStatusName(DmaStatus s);

/**
 * @brief Waveform resolution, in words.
 *
 * Each word is one DMA transfer and one timer tick. 128 gives a duty step of
 * 0.78 percent, comfortably finer than the twelve levels the discrimination run
 * showed to be distinguishable, for 512 bytes of RAM.
 */
constexpr size_t kWaveWords = 128;

class DmaPwm
{
public:
    /**
     * @brief Claim a timer and a DMA channel, build the waveform, verify, enable.
     * @param dutyPercent 0 to 100.
     * @param periodUs    Length of one full waveform pass.
     * @return Running on success. Anything else means nothing was enabled.
     */
    DmaStatus start(uint8_t dutyPercent, uint32_t periodUs, void (*sleepMs)(uint32_t));

    /// Change duty with the hardware still running. Rewrites the buffer only;
    /// the DMA is reading it continuously, so the change takes effect within one
    /// pass and costs one pass of memory writes and no reconfiguration.
    void setDuty(uint8_t dutyPercent);

    /// Re-arm the block-repeat counter before it expires. Cheap, and the only
    /// thing the CPU has to do while a waveform is running.
    void poll();

    /// Disable, wait for idle, restore every saved register, including clocks.
    void stop();

    DmaStatus status() const { return mStatus; }
    uint8_t   duty() const { return mDuty; }

    /// Which timer and channel were borrowed, for the record.
    uint8_t timerIndex() const { return mTimerIndex; }
    uint8_t channelIndex() const { return mChannel; }

    /// How many times the block-repeat counter has been re-armed.
    uint32_t rearms() const { return mRearms; }

    /// The timer's input clock, measured rather than assumed, in kHz.
    ///
    /// The first version took this to be the core clock and was wrong by about
    /// fifty times: the waveform came out at roughly 5 Hz instead of 250, which
    /// is a visible flash rather than a brightness. The timer sits on APB1 and
    /// whatever the kernel has done to that prescaler is not knowable from here,
    /// so it is measured the same way the core clock is.
    uint32_t timerKhz() const { return mTimerKhz; }

private:
    DmaStatus mStatus     = DmaStatus::Idle;
    uint8_t   mDuty       = 0;
    uint8_t   mTimerIndex = 0;   ///< 6 or 7.
    uint8_t   mChannel    = 0xFF;

    uint32_t mRearms   = 0;
    uint32_t mTimerKhz = 0;

    /// Saved before anything is written, restored by stop().
    uint32_t mSavedAhb1Enr  = 0;
    uint32_t mSavedApb1Enr1 = 0;
    bool     mTouchedClocks = false;
    bool     mConfigured    = false;

    bool pickTimer();

    /// Runs the timer briefly against the kernel's millisecond clock to find its
    /// input rate. Returns 0 if it does not count.
    uint32_t measureTimerKhz(void (*sleepMs)(uint32_t));
    bool pickChannel();
    void buildWave(uint8_t dutyPercent);

    /// Reads back every register written and compares. False aborts the start.
    bool verify(uint32_t periodUs) const;
};

} // namespace Pwm

#endif // DMA_PWM_HPP
