/**
 ******************************************************************************
 * @file    SoftPwm.hpp
 * @brief   Modulating one pin from the CPU, in slices short enough to be safe.
 ******************************************************************************
 *
 * PF3 has no timer output. ST's pin table for `STM32U5A5QJI` gives it
 * `LPTIM3_IN1` and nothing else timer-shaped, and `IN1` is a capture input, not
 * an output channel. So a duty cycle on this pin has to be generated by the CPU.
 *
 * ## Why it runs in bursts instead of a loop
 *
 * The obvious implementation is `while (running) { on; wait; off; wait; }`, and
 * it would reboot the watch. The kernel watches app threads for liveness, and a
 * long synchronous loop that never returns to the message queue is what tripped
 * that watchdog when MapManager verified a large pack.
 *
 * So `runBurst()` does a bounded amount of PWM and returns, and the service calls
 * it again from its own poll. The budget is tens of milliseconds, which is a few
 * cycles at a few hundred Hz. The gap between bursts is one pass through a
 * message queue that is almost always empty, which is far shorter than a PWM
 * period, so the light does not visibly flicker at the seams.
 *
 * That is also why the burst budget is a parameter rather than a constant: it is
 * the safety margin, and it belongs where a reader can see it being chosen.
 *
 * ## What "duty" means here, and the two ends of it
 *
 * `duty` is the percentage of each period the light is **on**, matching
 * `RequestBacklightSet::brightness` so the two can be compared directly.
 *
 * The endpoints are special-cased rather than left to the arithmetic:
 *
 *   - `duty == 0` holds the pin off for the whole burst and writes one edge, not
 *     a stream of zero-length pulses.
 *   - `duty == 100` holds it on for the whole burst, likewise.
 *
 * Without that, a 100 percent duty would still emit an off edge and an on edge
 * every period, and any glitch in the off-to-on transition would show up as a
 * dimming at full brightness, which is exactly the artefact that would discredit
 * the result.
 *
 * ## It spins only where it has to
 *
 * There is no sleep at microsecond resolution and no timer interrupt available to
 * an app, so the **on** phase is a busy wait on the cycle counter. That much is
 * unavoidable short of the DMA-driven waveform, which is the correct production
 * answer and a great deal more machinery.
 *
 * An **endpoint** duty (0 or 100) is the one case that costs nothing: the pin is
 * set and the call returns, because holding a level needs no CPU whatsoever.
 *
 * ## A modulated period spins, and cannot do otherwise
 *
 * Three placements of a sleep were tried inside this engine and all three failed,
 * for two reasons that between them rule the idea out on this kernel:
 *
 *   - **`ISystem::delay` has roughly millisecond granularity**, which is a
 *     quarter of the whole period. There is no way to place a 4 ms period's edges
 *     with a tool that coarse. Measured on hardware: `delay(1)` often returned
 *     almost immediately while `delay(2)` slept about 2 ms, so the same code gave
 *     75 percent duty at one rung and 18 percent at another.
 *   - **`DWT_CYCCNT` stops while the core sleeps**, so a spin after a sleep
 *     cannot tell how much of the period is left and spins the whole off phase
 *     again on top of it.
 *
 * So the on phase and the off phase are both spun, and a modulated rung costs a
 * full thread for its duration. The CPU is given back **between** rungs instead,
 * where a gap is invisible because the light is off anyway. See PwmPlan.hpp.
 *
 * The real answer remains the timer-driven DMA waveform, which needs neither the
 * CPU nor an accurate sleep.
 *
 ******************************************************************************
 */

#ifndef SOFT_PWM_HPP
#define SOFT_PWM_HPP

#include <cstdint>

#include "PwmPin.hpp"

namespace Pwm
{

/// What one burst did, so the results file can report the waveform actually
/// produced rather than the one that was asked for.
struct BurstStats {
    uint32_t periods   = 0; ///< Complete periods emitted.
    uint32_t onUs      = 0; ///< Total microseconds commanded on.
    uint32_t totalUs   = 0; ///< Total microseconds the burst covered.
    uint32_t edges     = 0; ///< Pin writes issued.

    /// True when the duty was an endpoint and the pin was simply set and left.
    /// The caller uses this to know it can sleep rather than call straight back:
    /// holding a level needs no CPU at all, and spinning to do it is what put the
    /// first version of this app at 100 percent for the whole ladder.
    bool held = false;

    /// Achieved duty in percent, from the microseconds actually spent rather
    /// than from the requested figure. A gap between this and the request is the
    /// interesting number: it is how much the busy wait and the message loop
    /// cost.
    uint8_t achievedPercent() const
    {
        return totalUs ? static_cast<uint8_t>((static_cast<uint64_t>(onUs) * 100u) / totalUs) : 0u;
    }
};

class SoftPwm
{
public:
    SoftPwm(IPin& pin, const IClock& clock);

    /// 0 to 100. Values above 100 are clamped; the plan never sends one, but a
    /// silent overflow into a tiny on-time would look like a hardware fault.
    void setDuty(uint8_t percent);
    uint8_t duty() const { return mDuty; }

    /// Period of one PWM cycle. Below about 100 Hz the eye sees flicker; above a
    /// few kHz the busy wait spends all its time in the loop overhead rather
    /// than in the delays.
    void setPeriodUs(uint32_t periodUs);
    uint32_t periodUs() const { return mPeriodUs; }

    /**
     * @brief Modulate for at most `maxPeriods` whole periods, then return.
     *
     * Counted in periods rather than microseconds because a period may now sleep
     * through its off phase, and the cycle counter stops while it does. A time
     * budget measured against that clock would run long by however much was
     * slept; a period count cannot.
     *
     * Always ends on a period boundary, so a burst never leaves the light on for
     * the length of the gap that follows it.
     *
     * At duty 0 and 100 it sets the pin and returns **immediately**, with
     * `BurstStats::held` set. There is nothing to modulate at an endpoint, and
     * the caller is expected to sleep rather than spin. Re-asserting the level
     * once per call is still worth doing: it is what overrides the kernel if the
     * kernel writes the pin during a held rung.
     */
    BurstStats runBurst(uint32_t maxPeriods);

    /// Leaves the light off. Called when the plan finishes and when the app is
    /// asked to stop.
    void off();

    /// Running totals across every burst, for the record.
    const BurstStats& totals() const { return mTotals; }

private:
    IPin&         mPin;
    const IClock& mClock;

    uint8_t  mDuty     = 0;
    uint32_t mPeriodUs = 4000; ///< 250 Hz.

    BurstStats mTotals;

    /// Spin until `deadlineUs` has passed. Returns the time it actually stopped
    /// at, which is at or after the deadline: the caller measures from that
    /// rather than from the deadline, so overshoot accumulates into the reported
    /// duty instead of being hidden.
    uint32_t spinUntil(uint32_t deadlineUs) const;

};

} // namespace Pwm

#endif // SOFT_PWM_HPP
