/**
 ******************************************************************************
 * @file    SoftPwm.hpp
 * @brief   Modulating one pin from the CPU, in slices short enough to be safe.
 ******************************************************************************
 *
 * PF3 has no timer output. ST's pin table for `STM32U5A5QJI` gives it
 * `LPTIM3_IN1` and nothing else timer-shaped, and `IN1` is a capture input, not
 * an output channel. So a duty cycle on this pin has to be generated by the CPU.
 *
 * ## Why it runs in bursts instead of a loop
 *
 * The obvious implementation is `while (running) { on; wait; off; wait; }`, and
 * it would reboot the watch. The kernel watches app threads for liveness, and a
 * long synchronous loop that never returns to the message queue is what tripped
 * that watchdog when MapManager verified a large pack.
 *
 * So `runBurst()` does a bounded amount of PWM and returns, and the service calls
 * it again from its own poll. The budget is tens of milliseconds, which is a few
 * cycles at a few hundred Hz. The gap between bursts is one pass through a
 * message queue that is almost always empty, which is far shorter than a PWM
 * period, so the light does not visibly flicker at the seams.
 *
 * That is also why the burst budget is a parameter rather than a constant: it is
 * the safety margin, and it belongs where a reader can see it being chosen.
 *
 * ## What "duty" means here, and the two ends of it
 *
 * `duty` is the percentage of each period the light is **on**, matching
 * `RequestBacklightSet::brightness` so the two can be compared directly.
 *
 * The endpoints are special-cased rather than left to the arithmetic:
 *
 *   - `duty == 0` holds the pin off for the whole burst and writes one edge, not
 *     a stream of zero-length pulses.
 *   - `duty == 100` holds it on for the whole burst, likewise.
 *
 * Without that, a 100 percent duty would still emit an off edge and an on edge
 * every period, and any glitch in the off-to-on transition would show up as a
 * dimming at full brightness, which is exactly the artefact that would discredit
 * the result.
 *
 * ## It is a busy wait, and that is deliberate
 *
 * There is no sleep an app can use at this resolution, and there is no timer
 * interrupt available to it. The CPU spins on the cycle counter. For a
 * proof of concept measured in seconds that is the right trade: the alternative
 * is a DMA-driven waveform, which is the correct production answer and a great
 * deal more machinery. See the README.
 *
 ******************************************************************************
 */

#ifndef SOFT_PWM_HPP
#define SOFT_PWM_HPP

#include <cstdint>

#include "PwmPin.hpp"

namespace Pwm
{

/// What one burst did, so the results file can report the waveform actually
/// produced rather than the one that was asked for.
struct BurstStats {
    uint32_t periods   = 0; ///< Complete periods emitted.
    uint32_t onUs      = 0; ///< Total microseconds commanded on.
    uint32_t totalUs   = 0; ///< Total microseconds the burst covered.
    uint32_t edges     = 0; ///< Pin writes issued.

    /// Achieved duty in percent, from the microseconds actually spent rather
    /// than from the requested figure. A gap between this and the request is the
    /// interesting number: it is how much the busy wait and the message loop
    /// cost.
    uint8_t achievedPercent() const
    {
        return totalUs ? static_cast<uint8_t>((static_cast<uint64_t>(onUs) * 100u) / totalUs) : 0u;
    }
};

class SoftPwm
{
public:
    SoftPwm(IPin& pin, const IClock& clock);

    /// 0 to 100. Values above 100 are clamped; the plan never sends one, but a
    /// silent overflow into a tiny on-time would look like a hardware fault.
    void setDuty(uint8_t percent);
    uint8_t duty() const { return mDuty; }

    /// Period of one PWM cycle. Below about 100 Hz the eye sees flicker; above a
    /// few kHz the busy wait spends all its time in the loop overhead rather
    /// than in the delays.
    void setPeriodUs(uint32_t periodUs);
    uint32_t periodUs() const { return mPeriodUs; }

    /**
     * @brief Modulate for at most `budgetUs`, then return.
     *
     * Stops at a period boundary when one falls inside the budget, so a burst
     * does not end mid-pulse and leave the light on for the length of the gap.
     */
    BurstStats runBurst(uint32_t budgetUs);

    /// Leaves the light off. Called when the plan finishes and when the app is
    /// asked to stop.
    void off();

    /// Running totals across every burst, for the record.
    const BurstStats& totals() const { return mTotals; }

private:
    IPin&         mPin;
    const IClock& mClock;

    uint8_t  mDuty     = 0;
    uint32_t mPeriodUs = 4000; ///< 250 Hz.

    BurstStats mTotals;

    /// Spin until `deadlineUs` has passed. Returns the time it actually stopped
    /// at, which is at or after the deadline: the caller measures from that
    /// rather than from the deadline, so overshoot accumulates into the reported
    /// duty instead of being hidden.
    uint32_t spinUntil(uint32_t deadlineUs) const;
};

} // namespace Pwm

#endif // SOFT_PWM_HPP
